### ISSUE TITLE
Not working after adding to template

### ISSUE THREAD

**Issue by DylanC** [photogabble/tagify-vue#5]
I have added tags manually to the tags array and the tags do not appear like the demo page:
https://yaireo.github.io/tagify/

![tagify-vue](https://user-images.githubusercontent.com/4488048/34102650-d29f274e-e3e1-11e7-8fc0-e33c4c102c11.png)

The component is definitely added to the project:

![image](https://user-images.githubusercontent.com/4488048/34102710-055ff21c-e3e2-11e7-95ed-0f020343dfd9.png)

**Comment by DylanC** [comment]
@carbontwelve - How do I debug this?

**Comment by DylanC** [comment]
@carbontwelve - Nevermind. I was just missing the requirejs:
`const Tagify = require('@yaireo/tagify/dist/tagify');`

**Comment by carbontwelve** [comment]
@DylanC im glad you found a solution :)

**Comment by DylanC** [comment]
@carbontwelve - Apologies for logging all the issues. I'm new to Vue.  :)
