### ISSUE TITLE
Tags not returned in IE11

### ISSUE THREAD

**Issue by DylanC** [photogabble/tagify-vue#7]
Add a tag to the Tagify component.

From the parent component (which contains Tagify) you can do:
`this.tags.length`

**Correct** - In Chrome this returns 1.
**Incorrect** - In IE11 this returns 0.

I already have a es6-shim in this project. Does IE11 need something else to run your plugin?

**Comment by carbontwelve** [comment]
Thank you for bringing this to my attention, I am going to put together a demo page with tagify-vue in it to see if I can reproduce and also see if it is a bug with my vue wrapper or the tagify base library itself.

**Comment by DylanC** [comment]
@carbontwelve 

It was just down to a missing shim actually. This shim will make IE11 give the same result as Chrome:

`<script type="text/javascript">
      (function () {
          if ( typeof window.CustomEvent === "function" ) return false; //If not IE

          function CustomEvent ( event, params ) {
            params = params || { bubbles: false, cancelable: false, detail: undefined };
            var evt = document.createEvent( 'CustomEvent' );
            evt.initCustomEvent( event, params.bubbles, params.cancelable, params.detail );
            return evt;
           }
          CustomEvent.prototype = window.Event.prototype;
          window.CustomEvent = CustomEvent;
        })();
    </script>`

Thanks anyway.
